### ISSUE TITLE
Opera don't show linear gradient 

### ISSUE THREAD

**Issue by f-liva** [TurbineCSS/Turbine#92]
The visualization technique svg does not work with Opera browser. You'll see a transparent background.

**Comment by Schepp** [comment]
This seems to be a "sometimes"-bug where Opera cuts off the path to the SVG at the first #-character. Will be fixed in the next release.

**Comment by Schepp** [comment]
Fixed for the next release!

**Comment by f-liva** [comment]
I have to launch new portal of www.jooforge.com and i would publicize your framework in the footer section. Can you give me the fix now please?

**Comment by Schepp** [comment]
Sure. You will need to download my fork then: http://github.com/Schepp/Turbine/archives/master

**Comment by f-liva** [comment]
Bug not fixed, is the same problem. :(

## background-image: linear-gradient(top,#fff,#e7e7e7)

background-image: url(/testing/templates/jf_jooforge/lib/turbine/plugins/backgroundgradient/svg.php?direction=top&startcolor=%23da1725&endcolor=%23b51020) 0 0 repeat;

The path is correct.

**Comment by Schepp** [comment]
If you call the SVG directly with Opera it should work (it worked for me here, red to winered gradient).

Can you send me a link? If not public then perhaps via Github message?

**Comment by Schepp** [comment]
Sorry: and which Opera version?

**Comment by f-liva** [comment]
Yes if i open directly the link now it works, but from the page nothing.
Give me one moment and i move the site in remote.

**Comment by f-liva** [comment]
I have do some tests, and we have find the problem:

1) The background gradient plugin print in any case background position and repeat. If in the cssp file i write "background-image" insted of "background" property, you have to print only "url(....)" portion, and not "url(....) 0 0 repeat"

2) The image now display correctly, i think was a Opera bug, because i have moved the gradient effect in "ul li a" element instead of "ul li" and now works correctly.

**Comment by Schepp** [comment]
Thanks a lot for your research! Makes sense. I changed it to url() only and you can find it again in my updated fork (again: http://github.com/Schepp/Turbine/archives/master)

**Comment by f-liva** [comment]
Perfect, now all is ok.

**Comment by SirPepe** [comment]
Schepp's patches e9cf517009a32760b70e and 0d905de559edbbbc6e51 are now in the main repository and will be shipped with the next version.

**Comment by SirPepe** [comment]
Fixed in 1.0.4
